# docker-compose.yml
version: '3'

services:
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    networks:
      - backend_redis
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  worker:
    container_name: worker
    restart: always
    build: ./app
    environment:
      - REDIS_HOST=redis
    networks:
      - backend_redis
    depends_on:
      - redis
    command: celery -A celery_worker.celery worker -l info
    volumes:
      - ./:/app/

networks:
  backend_redis: