# docker-compose.yml
version: '3'

services:
  #rabbitmq container
  rabbitmq:
    #use docker images
    image: rabbitmq:3-management
    restart: always
    #ports setting
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - backend_cache
    #volumes setting
    # volumes:
      # - ./mq-data:/var/lib/rabbitmq

  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    sysctls:
      net.core.somaxconn: '65535'
    networks:
      - backend_cache
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf

#  worker:
#    container_name: worker
#    restart: always
#    build: .
#    environment:
#      - REDIS_HOST=redis
#    networks:
#      - backend_redis
#    depends_on:
#      - redis
#    command: celery -A manager.celery worker -l info
#    volumes:
#      - ./:/app/

networks:
  backend_cache:
